services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
    ports:
      - ${FLARESOLVERR_PORT:-8191}:8191
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: false